// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSelection() {
  return window['go']['main']['App']['CancelSelection']();
}

export function Capture() {
  return window['go']['main']['App']['Capture']();
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function CloseSettings() {
  return window['go']['main']['App']['CloseSettings']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DisplayCount() {
  return window['go']['main']['App']['DisplayCount']();
}

export function FinishSelection() {
  return window['go']['main']['App']['FinishSelection']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetView() {
  return window['go']['main']['App']['GetView']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ListDicts() {
  return window['go']['main']['App']['ListDicts']();
}

export function ListDisplays() {
  return window['go']['main']['App']['ListDisplays']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveCSV(arg1, arg2) {
  return window['go']['main']['App']['SaveCSV'](arg1, arg2);
}

export function SaveSessionSummary(arg1, arg2) {
  return window['go']['main']['App']['SaveSessionSummary'](arg1, arg2);
}

export function SessionFrame(arg1) {
  return window['go']['main']['App']['SessionFrame'](arg1);
}

export function SessionFrameCount() {
  return window['go']['main']['App']['SessionFrameCount']();
}

export function SetViewByName(arg1) {
  return window['go']['main']['App']['SetViewByName'](arg1);
}

export function StartSession() {
  return window['go']['main']['App']['StartSession']();
}

export function StopSession() {
  return window['go']['main']['App']['StopSession']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
