// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Capture():Promise<void>;

export function HideWindow():Promise<void>;

export function Quit():Promise<void>;
