// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelSelection():Promise<void>;

export function Capture():Promise<void>;

export function ClearSession():Promise<void>;

export function FinishSelection():Promise<void>;

export function HideWindow():Promise<void>;

export function Quit():Promise<void>;

export function SessionFrame(arg1:number):Promise<main.FrameMeta>;

export function SessionFrameCount():Promise<number>;

export function StartSession():Promise<void>;

export function StopSession():Promise<number>;
