// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSelection() {
  return window['go']['main']['App']['CancelSelection']();
}

export function Capture() {
  return window['go']['main']['App']['Capture']();
}

export function FinishSelection() {
  return window['go']['main']['App']['FinishSelection']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}
