// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelSelection():Promise<void>;

export function Capture():Promise<void>;

export function ClearSession():Promise<void>;

export function CloseSettings():Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DisplayCount():Promise<number>;

export function FinishSelection():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetView():Promise<string>;

export function HideWindow():Promise<void>;

export function ListDicts():Promise<Array<string>>;

export function ListDisplays():Promise<Array<main.DisplayInfo>>;

export function ListSessions():Promise<Array<main.SessionMeta>>;

export function LoadSession(arg1:string):Promise<main.SessionRecord>;

export function OpenSettings():Promise<void>;

export function Quit():Promise<void>;

export function SaveCSV(arg1:string,arg2:string):Promise<string>;

export function SaveSessionSummary(arg1:number,arg2:Array<main.SessionWord>):Promise<string>;

export function SessionFrame(arg1:number):Promise<main.FrameMeta>;

export function SessionFrameCount():Promise<number>;

export function SetViewByName(arg1:string):Promise<void>;

export function StartSession():Promise<void>;

export function StopSession():Promise<number>;

export function UpdateConfig(arg1:main.Config):Promise<void>;
